apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"3"},"generation":3,"name":"api-gateway","namespace":"default","resourceVersion":"126348","uid":"a13ac7f7-73f3-4b2f-9ea9-79a50668e5a5"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"api-gateway"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2025-03-26T18:11:11-05:00","linkerd.io/inject":"enabled"},"labels":{"app":"api-gateway"}},"spec":{"containers":[{"env":[{"name":"OTEL_EXPORTER_OTLP_ENDPOINT","value":"http://otel-collector:4317"}],"image":"localhost:5000/api-gateway:latest","imagePullPolicy":"IfNotPresent","name":"api-gateway","ports":[{"containerPort":3000,"protocol":"TCP"}],"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"250m","memory":"128Mi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"message":"ReplicaSet \"api-gateway-7d96f57cdf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"},{"message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"}],"observedGeneration":3,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2025-03-26T22:16:27Z"
  generation: 4
  name: api-gateway
  namespace: default
  resourceVersion: "126545"
  uid: a13ac7f7-73f3-4b2f-9ea9-79a50668e5a5
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: api-gateway
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-03-26T18:11:11-05:00"
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: api-gateway
    spec:
      containers:
      - env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4317
        image: localhost:5000/api-gateway:latest
        imagePullPolicy: IfNotPresent
        name: api-gateway
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-03-26T22:16:27Z"
    lastUpdateTime: "2025-03-26T23:11:14Z"
    message: ReplicaSet "api-gateway-7d96f57cdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-03-26T23:15:31Z"
    lastUpdateTime: "2025-03-26T23:15:31Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
