# Etapa de compilación
FROM node:18 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# Etapa de ejecución
FROM node:18-slim

WORKDIR /app
COPY --from=builder /app/dist /app
COPY package*.json ./
RUN npm install --production

EXPOSE 8080
CMD ["node", "index.js"]
