apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-1-deployment
  labels:
    app: micro-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-1
  template:
    metadata:
      labels:
        app: micro-1
    spec:
      containers:
      - name: micro-1
        image: localhost:5000/micro-1:latest # Imagen desde el registro local
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger:14268/api/traces"
        - name: OTEL_SERVICE_NAME
          value: "micro-1"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: micro-1
spec:
  selector:
    app: micro-1
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
