FROM rust:1.82.0 AS builder

WORKDIR /app
COPY . .

RUN apt-get update && apt-get install -y protobuf-compiler && \
    export PROTOC=/usr/bin/protoc
RUN cargo build --release

FROM ubuntu:22.04

RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /app/target/release/micro-1 /usr/local/bin/micro-1

EXPOSE 50051

CMD [ "micro-1" ]
