apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-2-deployment
  labels:
    app: micro-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-2
  template:
    metadata:
      labels:
        app: micro-2
    spec:
      containers:
      - name: micro-2
        image: localhost:5000/micro-2:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
        ports:
        - containerPort: 50051 # Cambia al puerto que expone la aplicación, si es diferente
        env:
        - name: OTEL_EXPORTER_JAEGER_ENDPOINT
          value: "http://jaeger:14268/api/traces"
        - name: SERVICE_NAME
          value: "micro-2"
        readinessProbe:
          httpGet:
            path: /
            port: 50051 # Cambia al puerto correcto si es necesario
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 50051 # Cambia al puerto correcto si es necesario
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: micro-2
spec:
  selector:
    app: micro-2
  ports:
  - name: "grpc-collector"
    protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP
