# Etapa de compilación
FROM golang:1.23 AS builder

WORKDIR /app

# Instalar protoc y dependencias
RUN apt-get update && apt-get install -y protobuf-compiler protoc-gen-go protoc-gen-go-grpc

# Copiar archivos de Go y descargar dependencias
COPY go.mod ./
COPY go.sum ./
RUN go mod tidy

# Instalar herramientas de generación de código
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

COPY . .

# Generar código protobuf
RUN protoc --go_out=. --go_opt=paths=source_relative \
           --go-grpc_out=. --go-grpc_opt=paths=source_relative \
           proto/micro.proto

# Compilar el binario
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o micro-2 .

# Imagen final
FROM ubuntu:22.04
WORKDIR /root/
COPY --from=builder /app/micro-2 .
CMD ["./micro-2"]
